variables:
  GITHUB_REPO: "gitlab.tavant.com/TWMS_MCF/MCF-QA-P2.git"
  REPOSITORY_NAME: "MCF-QA-P2"
  DEFAULT_BRANCH:
    value: "MCF-DEV-P2_Prasanth"
    description: "Enter the branch name"
  MAVEN_SETTINGS: /home/gitlab-runner/maven-settings-files/twms-mcf-tracs-setting.xml
  MAVEN_REPO: /home/gitlab-runner/maven-settings-files/twms-mcf-tracs-qa
  DEPLOY_SERVER: "twmsuser@10.129.146.218"
  DEPLOY_PATH_WARS: /home/twmsuser/ci
  DEPLOY_SCRIPT: /home/btprojusr01/apps/ci/deploy_util/scripts/deployer.sh

stages:
  - clone
  - deploy

default:
  before_script:
    - echo "Pipeline triggered by:$GITLAB_USER_NAME"
    - echo "Cloning repository from branch:$DEFAULT_BRANCH"
    - |
      if [[ -n "$twms_irw_uat_keys" ]]; then
        echo "$twms_irw_uat_keys" > /home/gitlab-runner/twms_irw_uat_keys.pem
        chmod 600 /home/gitlab-runner/twms_irw_uat_keys.pem
      fi
    - export JAVA_HOME=/opt/zulu8.76.0.17-ca-jdk8.0.402-linux_x64
    - export MAVEN_HOME=/opt/apache-maven-3.9.9
    - export M2_HOME=/opt/apache-maven-3.9.9
    - export PATH=$M2_HOME/bin:$JAVA_HOME/bin:$PATH
    - mvn -version
  tags:
    - Linux

clone_job:
  stage: clone
  tags:
   - genai-docker
  script:
    - git clone --branch "$DEFAULT_BRANCH" https://devtools:$GITLAB_PAT@$GITHUB_REPO
    - cd "$REPOSITORY_NAME"
    - find . -name "*.webapp-structure.xml" -delete

    # Build integration/bods
    - mvn -s $MAVEN_SETTINGS clean install -Dmaven.repo.local=$MAVEN_REPO -f integration/bods/pom.xml

    # Daily QA build
    - mvn -s $MAVEN_SETTINGS clean install -Pdailyqabuild -Dmaven.test.skip=true -Dmaven.repo.local=$MAVEN_REPO

    # Build integration/server
    - mvn -s $MAVEN_SETTINGS clean install -Dmaven.repo.local=$MAVEN_REPO -f integration/server/pom.xml

    # Deploy WARs
    - ./deploy_to_server.sh "$DEPLOY_SERVER" "$DEPLOY_PATH_WARS" /home/gitlab-runner/twms_irw_uat_keys.pem "$DEPLOY_SCRIPT"

  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
      when: on_success
    - when: manual
