image: maven:3.3.9-jdk-8

variables:
  GITHUB_REPO: "git@github.com:DoosanICA/db-irw.git"
  REPOSITORY_NAME: "db-irw"
  DEFAULT_BRANCH:
    value: "develop"
    description: "Enter the branch name"
  DependecyCheckRequired:
    description: "Select the option"
    value: "true"  # Default value
    options:
      - "flase"
      - "true"
  SonarQubeScanner:
    description: "Select the option"
    value: "true"  # Default value
    options:
      - "flase"
      - "true"
  Checkmarx:
    description: "Select the option"
    value: "true"  # Default value
    options:
      - "flase"
      - "true"
  MAVEN_SETTINGS_PATH: /home/gitlab-runner/maven-settings-files/twms-bobcat-irw-setting.xml -U clean install -Dmaven.test.skip=true
  MAVEN_REPO_LOCAL: /home/gitlab-runner/maven-settings-files/twms_bobcat_irw
  DEPENDENCY_CHECK_VERSION: "8.0.0"
  SONARQUBE_SCANNER_VERSION: "3.2.0"
  SONARQUBE_SERVER_URL: "https://sonar.tavant.com"
  SONARQUBE_PROJECT_KEY: "TWMS-Bobcat-IRW"
  SONARQUBE_TOKEN: "sqa_ed55584bea441804ed8b9fcf2c6f671137b971eb"
  CHECKMARX_SERVER_URL: "https://cxscan.tavant.com/"
  CHECKMARX_REPOSITORY_NAME: "TWMS-Bobcat-IRW-SonarQubeScan"
  CHECKMARX_TEAM: "\\CxServer"
  CHECKMARX_PRESET: "Checkmarx Default"
  EXCLUDE_PATTERNS: "!**/_cvs/**/*, !**/.svn/**/*, !**/.hg/**/*, !**/.git/**/*, !**/.bzr/**/*,
        !**/.gitgnore/**/*, !**/.gradle/**/*, !**/.checkstyle/**/*, !**/.classpath/**/*, !**/bin/**/*,
        !**/obj/**/*, !**/backup/**/*, !**/.idea/**/*, !**/*.DS_Store, !**/*.ipr, !**/*.iws,
        !**/*.bak, !**/*.tmp, !**/*.aac, !**/*.aif, !**/*.iff, !**/*.m3u, !**/*.mid, !**/*.mp3,
        !**/*.mpa, !**/*.ra, !**/*.wav, !**/*.wma, !**/*.3g2, !**/*.3gp, !**/*.asf, !**/*.asx,
        !**/*.avi, !**/*.flv, !**/*.mov, !**/*.mp4, !**/*.mpg, !**/*.rm, !**/*.swf, !**/*.vob,
        !**/*.wmv, !**/*.bmp, !**/*.gif, !**/*.jpg, !**/*.png, !**/*.psd, !**/*.tif, !**/*.swf,
        !**/*.jar, !**/*.zip, !**/*.rar, !**/*.exe, !**/*.dll, !**/*.pdb, !**/*.7z, !**/*.gz,
        !**/*.tar.gz, !**/*.tar, !**/*.gz, !**/*.ahtm, !**/*.ahtml, !**/*.fhtml, !**/*.hdm,
        !**/*.hdml, !**/*.hsql, !**/*.ht, !**/*.hta, !**/*.htc, !**/*.htd, !**/*.war, !**/*.ear,
        !**/*.htmls, !**/*.ihtml, !**/*.mht, !**/*.mhtm, !**/*.mhtml, !**/*.ssi, !**/*.stm,
        !**/*.bin,!**/*.lock,!**/*.svg,!**/*.obj,
        !**/*.stml, !**/*.ttml, !**/*.txn, !**/*.xhtm, !**/*.xhtml, !**/*.class, !**/*.iml, !Checkmarx/Reports/*.*,
        !OSADependencies.json, !**/node_modules/**/*
        !**/help/**/*, !**/vendor/**/*, !**/*.bat, !**/*.vm, !**/*.properties, !**/*.jrxml, !**/*.jasper, !**/*.xsl, !**/dbpatches/**/*"
        
stages:
  - checkmarx-scan

sonarqube_scan:
  stage: sonarqube
  image: maven:3.8.8-openjdk-11 # Use Maven with JDK 11

    




  artifacts:
    paths:
      - reports/



